Repository flathub/org.gimp.GIMP, pull requests merged in 2025-06, with the labels that each got.

#437 Enable dependency updates for both branches
  .github/workflows/update.yaml
  flathub.json
Labels: enhancement, 1. Stable, 1. Beta

#444 .github: Enable per branch update check on Beta
  .github/workflows/update.yaml
  org.gimp.GIMP.json
Labels: enhancement, 1. Beta

#447 flathub: Add comment about why we disable flathubbot
  flathub.json
Labels: 1. Stable

#460 manifest: Restrict Gexiv2 module version to the API we support
  org.gimp.GIMP.json
Labels: 1. Stable
